config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions

  root  'static_pages#home'

  get    '/home',   to: 'static_pages#home'
  get    '/secret', to: 'static_pages#secret',   as: 'secret'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  first_name :string
#  last_name  :string
#  user_email :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ApplicationRecord
  before_save {self.user_email = user_email.downcase}

  Email_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :user_email, presence: true,
                    format: {with: Email_REGEX},
                    uniqueness: {case_sensitive: false}

  validates :first_name, presence: true
  validates :last_name,  presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(id: params[:session][:user_id])
    if user
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'ID invalide'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def secret
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash.now[:succes] = "Hey, Bienvenue #{@user.first_name} !"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :user_email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end


  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Club Privé", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Accueil", root_path %></li>
        <% if logged_in? %>
              <ul class="nav navbar-nav navbar-right">
                <li>
                  <%= link_to "Se déconnecter", logout_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Se connecter", login_path %></li>
            <li><%= link_to "S'inscrire", new_user_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Le Club Privé</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
   </head>
   <body>
     <%= render 'layouts/header' %>
     <div class="container">
       <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
       <%= yield %>
     </div>
   </body>
 </html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Vous êtes sur la page d'accueil d'un club privé</h1>

    <%= link_to('Entrer dans le club privé', secret_path, class: "btn btn-lg btn-primary") %>
  </div>
</div>

app/views/static_pages/secret.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

      <% if logged_in? %>

        <h3 class="text-center"><%= "Bienvenue #{@current_user.first_name} ..."%></h3>
        <table class="table">
          <thead>
            <tr>
              <th>Prénom</th>
              <th>Nom</th>
              <th>Email</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= user.first_name %></td>
                <td><%= user.last_name %></td>
                <td><%= user.user_email %></td>
              </tr>
              <% end %>
          </tbody>
        </table>

      <% else %>

        <p class="text-center">Il semblerait que tu ne connaisse pas le dresscode mecton !! Connecte-toi d'abord !</p>
        <%= link_to('Se connecter', new_session_path, :class => "btn btn-secondary btn-lg btn-block") %>

      <%end%>
  <div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Inscris toi !') %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :first_name, "Quel est ton prénom ?" %>
      <%= f.text_field :first_name, class: 'form-control' %>

      <%= f.label :last_name, "Quel est ton nom ?" %>
      <%= f.text_field :last_name, class: 'form-control' %>

      <%= f.label :user_email, "Quel est ton email ?" %>
      <%= f.email_field :user_email, class: 'form-control' %>

      <%= f.submit "Créer mon compte", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1><%= "Hey #{@user.first_name} !"%></h1>
    <h2>Bienvenue dans le club ultra privé !</h2>
    <p><%= "Ton ID est #{@user.id}, ne l'oublie pas !"%></br>
    <p>Tu en auras besoin pour tes prochaines connections !</p>
  </div>
</div>